import test from "node:test";
import assert from "node:assert/strict";
import { GitHubClient } from "../src/github.ts";

const repo = { owner: "example", name: "repo", nameWithOwner: "example/repo", host: "github.com" };

function clientWithResponses(reviews: unknown[], reviewThreads: unknown[]) {
	const calls: string[][] = [];
	const pi = {
		exec: async (_command: string, args: string[]) => {
			calls.push(args);
			if (args.includes("graphql")) {
				return {
					code: 0,
					stderr: "",
					stdout: JSON.stringify({
						data: {
							repository: {
								pullRequest: {
									reviewThreads: {
										pageInfo: { hasNextPage: false, endCursor: null },
										nodes: reviewThreads,
									},
								},
							},
						},
					}),
				};
			}
			return { code: 0, stderr: "", stdout: JSON.stringify([reviews]) };
		},
	};
	return { client: new GitHubClient(pi as any, "/tmp", repo), calls };
}

test("previous agentic review with unresolved review threads blocks another review", async () => {
	const { client } = clientWithResponses(
		[
			{
				body: "_Generated by the pi LangGraph agentic-review workflow._",
				state: "CHANGES_REQUESTED",
				submitted_at: "2026-07-14T12:00:00Z",
				commit_id: "abc123",
				user: { login: "reviewer" },
				html_url: "https://github.com/example/repo/pull/1#pullrequestreview-1",
			},
		],
		[
			{
				isResolved: false,
				path: "src/file.ts",
				line: 42,
				comments: { nodes: [{ author: { login: "reviewer" }, url: "https://github.com/example/repo/pull/1#discussion_r1" }] },
			},
			{
				isResolved: true,
				path: "src/ok.ts",
				line: 7,
				comments: { nodes: [{ author: { login: "reviewer" }, url: "https://github.com/example/repo/pull/1#discussion_r2" }] },
			},
		],
	);

	const blocker = await client.getPreviousAgenticReviewBlocker(1);
	assert.equal(blocker?.latestReview.headSha, "abc123");
	assert.equal(blocker?.unresolvedThreadCount, 1);
	assert.deepEqual(blocker?.unresolvedThreads[0], {
		path: "src/file.ts",
		line: 42,
		author: "reviewer",
		url: "https://github.com/example/repo/pull/1#discussion_r1",
	});
});

test("previous agentic review with all review threads resolved does not block", async () => {
	const { client } = clientWithResponses(
		[
			{
				body: "_Generated by the pi LangGraph agentic-review workflow._",
				submitted_at: "2026-07-14T12:00:00Z",
				user: { login: "reviewer" },
			},
		],
		[
			{
				isResolved: true,
				path: "src/file.ts",
				line: 42,
				comments: { nodes: [{ author: { login: "reviewer" }, url: "https://github.com/example/repo/pull/1#discussion_r1" }] },
			},
		],
	);

	assert.equal(await client.getPreviousAgenticReviewBlocker(1), undefined);
});

test("PRs without a previous agentic review do not query review threads", async () => {
	const { client, calls } = clientWithResponses(
		[
			{
				body: "Looks good to me.",
				submitted_at: "2026-07-14T12:00:00Z",
				user: { login: "human" },
			},
		],
		[],
	);

	assert.equal(await client.getPreviousAgenticReviewBlocker(1), undefined);
	assert.equal(calls.some((args) => args.includes("graphql")), false);
});
